package:
  name: mpifft4py
  version: "{{ GET_DESCRIBE_TAG }}"

source:
  git_url: ../../

build:
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - numpy
    - scipy
    - mpi4py
    - fftw
    - pyfftw

test:
  source_files:
    - tests

  requires:
    - pytest
